### ISSUE TITLE
Multiple Choice Radio Button does not function when answers are integer values.

### ISSUE THREAD

**Issue by SchmidtNikolas** [drjeffjackson/GUIWorK#1]
WeBWorK tries to read integer values as indices and fails to accept integer values as appropriate answers to MCRB questions. Reproduce with attached problem.
[mcrb_issue.def.txt](https://github.com/drjeffjackson/GUIWorK/files/4582759/mcrb_issue.def.txt)

**Comment by SchmidtNikolas** [comment]
Looks like there was [a "noindex" option added to MCRB questions to fix this](https://github.com/openwebwork/pg/commit/5f5f3a1eb9c44d350c43e4a0b8cd255a136caa72#diff-a2b4387aa26d2626acf19157cb3f2004). Been trying to work this into the system but it's not working too well. Maybe our WeBWorK runs a version from before this was added?

**Comment by SchmidtNikolas** [comment]
Yeah, looks like the above was on a PG 2.15 build that was never merged with WeBWorK master branch. Probably best to incorporate a fix that uses that notation.

**Comment by SchmidtNikolas** [comment]
Currently running WeBWorK's development branch on Ubuntu 20.04 with developmental PG  following the [Docker install instructions](https://github.com/openwebwork/webwork2/wiki/Docker-newbie-instructions). I'm still trying to get the `noindex` option to work. It's still throwing errors trying to read an integer value passed to `order` as an index regardless of whether or not it's quoted. I'll have to dig into [the PG source](https://github.com/openwebwork/pg/blob/master/macros/parserRadioButtons.pl) to make the `order` option check if the `noindex` option is set. Shouldn't be too hard, but I just don't want to spend my afternoon looking into the Perl side of things today.

@drjeffjackson Perhaps we should have something run through every single option available (have the UI read the source files for each problem type) and create a GUI through that so that all the options are available to everyone? Or at least determine which options are basic and which are for an "advanced" menu? Thoughts on this?

**Comment by SchmidtNikolas** [comment]
[Committed a fix for this to dev.](https://github.com/drjeffjackson/GUIWorK/commit/bf9e5a8d294c0ae3e46cc37922d1b2b5a9620ae7) The `order` option discussed before turned out to be around strictly for comparability reasons, and it's not necessary to specify anymore. (With PG 2.15+ at least.) I removed that and added an internal verification step to check whether or not we needed `noindex` set to 0 or 1.

**Comment by drjeffjackson** [comment]
Could you sketch out how you see the options GUI looking?  One of my goals is to have something that's simple to use for the casual user, that makes typical choices for the user rather than burdening them with this.  That said, it would be nice to have power user features, such as being able to set options.

**Comment by SchmidtNikolas** [comment]
@drjeffjackson Here's a quick rendition of how I envision this looking. Obviously this is just a horrible mock-up, but I'd like the GUIWorK tools embedded alongside the editor in WeBWorK itself. (Altered to look prettier than this does right now.) We can have basic options visible by default, perhaps another drop-down toolbar or something to allow access to some power-user tools as well. This would all be integrated using the native text field on the left as opposed to GUIWorK's text field to reduce redundency and allow for power users to edit the raw problem code.

![image](https://user-images.githubusercontent.com/25828753/82758596-6b1e2300-9db5-11ea-81af-b95a3651d467.png)

I've been digging through all the Perl, trying to see if there's an effective means by which to incorporate GUIWorK into it. Unfortunately I'm still rather lost in much of it. I think for now, my plan will be to simply get the current JavaScript version integrated into this version of WeBWorK and then maybe after that, assuming I have time, I can work on porting it to Perl. 

And apologies for the slow response on this. I had a really busy week these past couple of days. Let me know what your thoughts are!

**Comment by drjeffjackson** [comment]
I like that approach, and I think that this is a good focus!  Here are a few thoughts:
1. I would not be concerned about porting the JavaScript to Perl. 
2. As part of the integration, it would be great if we could get away from the current kludge of saving GUIWorK data as HTML.  Much better to extract the necessary data from the page and save it as JSON.  This should allow us to get away from separate code for separate versions.
3. Adding power options should take a back seat to the first two points for now, I think.

**Comment by SchmidtNikolas** [comment]
Closing this issue because the discussion is creeping out of scope. Created a project to more appropriately manage discussion and visualize progress.
